services:
  pat_server:
    container_name: pat_server
    build:
      context: .
      dockerfile: Dockerfile.patServer
      tags:
        - patserver
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    environment:
      - ROOT=/prox/proxdata
      - AUTH_SERVER_URL=${AUTH_SERVER_URL}
      - API_PORT=${API_PORT}
    networks:
      - cpas

  pat_client:
    container_name: pat_client
    build:
      context: ../patClient
      dockerfile: Dockerfile.patClient
      tags:
        - patclient
    restart: unless-stopped
    ports:
      - ${GUI_PORT}:${GUI_PORT}
    env_file:
      - .env
    environment:
      - REACT_APP_AUTH_SERVER_URL=${AUTH_SERVER_URL}
      - REACT_APP_API_URL=http://${HOST}:${API_PORT}
    networks:
      - cpas


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    restart: unless-stopped
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Madrid
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: 192.168.1.5
    ports:
        - 8443:8443
        - 8081:8081
        - 9000:9000
    networks:
      - cpas


networks:
  cpas:
    external: true
